describe('Teste PagMenos', function() {

    beforeEach(() => {
        cy.visit('https://homologd.encinterativa.com.br/pagueMenos2024/home/')
        cy.title().should('be.equal', 'Promoção Saúde Premiada Pague Menos, Cimed e Extrafarma')
      })
    
    

    it('Valida se o form aceita campos preenchidos em formato inválido, e se retorna mensagens de erro', function(){
        cy.get('body > div.enc--wrapper > div.info-cookies > div > div > div > div:nth-child(2) > div > button').click()
        cy.get('.only-desk-flex--lg > div > .navbar-nav > .nav-item > .nav-link').click()
        cy.get('#novo_cpf').type('srgtewrgt')
        cy.get('#input-cpf-new-feedback').should('be.visible')
        cy.get('#novo_cpf').clear().type('561.500.297-27')
        cy.get('body > div.enc--wrapper > div.page--login.wrapper-login.page-internas > div > div > div > div > div > div > form > div.login-footer.d-flex.align-items-center.justify-content-center.flex-column > button').click()
        cy.get('#part_nome').type('123', {force: true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(1) > div:nth-child(2) > div > div.error-form.error-back').should('be.visible')
        cy.get('#part_data_nascimento').type('sdfcsdfc', {force: true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(1) > div:nth-child(3) > div > div.error-form.error-back').should('be.visible')
        cy.get('#vs1__combobox > .vs__selected-options > .vs__search').click({force: true})
        cy.get('#vs1__option-0').click({force: true})
        cy.get('#part_cep').type('06606300', {force: true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(2) > div:nth-child(1) > div > div > div > button').click({force: true})
        cy.wait(500)
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(2) > div:nth-child(1) > div > div.error-form.error-back').should('be.visible')
        cy.get('#part_numero').type('500', {force:true})
        cy.get('#email').type('futjtdyujdetruy', {force:true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(4) > div:nth-child(1) > div > div.error-form.error-back').should('be.visible')
        cy.get('#email_confirmation').type('cleber+1914@encinterativa.com.br', {force:true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(4) > div:nth-child(2) > div > div.error-form.error-back').should('be.visible')
        cy.get('#part_telefone1').type('rt5ygrtyg', {force:true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(4) > div:nth-child(3) > div > div.error-form.error-back').should('be.visible')
        cy.get('#password').type('yujmnhgtnf', {force:true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(6) > div:nth-child(1) > div > div.error-form.error-back').should('be.visible')
        cy.get('#password_confirmation').type('Senha123', {force:true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(6) > div:nth-child(2) > div > div.error-form.error-back').should('be.visible')
    })

    it('Preenche os campos do form de cadastro corretamente', function() {
        cy.get('body > div.enc--wrapper > div.info-cookies > div > div > div > div:nth-child(2) > div > button').click()
        cy.get('.only-desk-flex--lg > div > .navbar-nav > .nav-item > .nav-link').click()
        cy.get('#novo_cpf').type('561.500.297-27')
        cy.get('body > div.enc--wrapper > div.page--login.wrapper-login.page-internas > div > div > div > div > div > div > form > div.login-footer.d-flex.align-items-center.justify-content-center.flex-column > button').click()
        cy.get('#part_nome').type('Teste Cypress', {force: true})
        cy.get('#part_data_nascimento').type('12041992', {force: true})
        cy.get('#vs1__combobox > .vs__selected-options > .vs__search').click({force: true})
        cy.get('#vs1__option-0').click({force: true})
        cy.get('#part_cep').type('58053-008', {force: true})
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(2) > div:nth-child(1) > div > div > div > button').click({force: true})
        cy.wait(500)
        cy.get('#part_numero').type('500', {force:true})
        cy.get('#email').type('cleber+191114@encinterativa.com.br', {force:true})
        cy.get('#email_confirmation').type('cleber+191114@encinterativa.com.br', {force:true})
        cy.get('#part_telefone1').type('11947622858', {force:true})
        cy.get('#password').type('Senha123', {force:true})
        cy.get('#password_confirmation').type('Senha123', {force:true})
        cy.get('#novidades').check({force:true})
        cy.get('#part_regulamento').check({force:true})
        cy.wait(15000)
        cy.get('body > div.enc--wrapper > div.page--cadastro.wrapper-cadastro.page-internas > div > div.wrapper-cadastro-body.mt-4 > form > div:nth-child(9) > button').click({force:true})
    })

  })